#!/bin/bash
echo "================ Spotify Command Line Help Menu ================"
echo "  "
echo "================ Available commands ========================="
echo ""
echo " spotify play or spp => Plays the current song or opens the app if closed." 
echo "=========================================================================="
echo " spotify pause or sppa =>Pauses the current song"
echo "=========================================================================="
echo " spotify next or spn => Plays the next song in the current playlist "
echo "=========================================================================="
echo " spotify previous or sppr => Plays the previous song in the current playlist"
echo "=========================================================================="
echo "spotify play list or spl => Plays a given list"
echo "=========================================================================="
echo "spotify play artist or spa => Plays a given artist"
echo "=========================================================================="
echo " spotify status or sps => Shows the player current status"
echo "=========================================================================="
echo "spotify toggle shuffle or spran => Toggles shuffle mode"
echo "======================================================================="
echo "spotify toggle repeat or sprep => Toggle repeat mode"
echo "========================================================================"
echo "spotify vol or spv => Show actual volume level"
echo "========================================================================"
echo "spotify vol up or spvu => Rises volume"
echo "========================================================================"
echo "spotify vol down or spvd => Decreses volume"
echo "========================================================================"
echo "spotify showhelp or sph => Shows this menu"
echo ""
echo "================ Spotify Command Line Help Menu ================"
